### ISSUE TITLE
z-index of children issue

### ISSUE THREAD

**Issue by joemillervi** [thmsgbrt/react-simple-pull-to-refresh#13]
Hey, great package! This z-index is problematic because it is a global style. It puts the children in the pull to refresh above other stuff on the page (if the other stuff has zindex < 1) Is this needed?

line: https://github.com/thmsgbrt/react-simple-pull-to-refresh/blob/7534484723d12a3ddb3b544bbc9fd2af045b07d6/src/styles/main.scss#L8

**Comment by thmsgbrt** [comment]
Hi @joemillervi,
I'll give it a loot asap, thanks for the feedbacks!

**Comment by thmsgbrt** [comment]
Hey @joemillervi,
I tried to remember why I initially put it there and I can't really find a justification.
Do you confirm that removing this z-index solves your problem and doesn't create unwanted side-effect?
If so, I'm going to release an update as soon as you answer.

**Comment by thmsgbrt** [comment]
Hi!
I published 1.2.1, which removes unnecessary z-index.
Now closing this, thanks!
