### ISSUE TITLE
pullingContent get default content sometimes

### ISSUE THREAD

**Issue by Padi-dev-hoangdv** [thmsgbrt/react-simple-pull-to-refresh#17]
I changed `pullingContent=""` but still sometimes got text "pull to refresh" showing in mobile webview?.
How can I fix it?

**Comment by thmsgbrt** [comment]
Hi @Padi-dev-hoangdv 

This default message is only shown when the **pullingContent** prop is not provided.
Are you sure you are not doing anything specific with this property?

It would be nice to have a way to reproduce, if you have the time.
