### ISSUE TITLE
undefined is not an object (evaluating 'f().then')

### ISSUE THREAD

**Issue by JMorocho23** [thmsgbrt/react-simple-pull-to-refresh#20]
First of all thank you for this awesome library!

Been using this library but currently experiencing this error on-refresh seems to be a error tied to sentry, tried updating sentry dependencies but no luck.
![image](https://user-images.githubusercontent.com/26604996/108903930-df5b5080-75eb-11eb-873c-b317a895ffec.png)

![image](https://user-images.githubusercontent.com/26604996/108903304-2bf25c00-75eb-11eb-88f7-fbe8dbe8e6ff.png)

**Comment by thmsgbrt** [comment]
Hi @JMorocho23, thanks for appreciating the library :)

I could definitely use optional chaining here, to make sure that it is defined but onRefresh prop should always be defined.

Do you have a use case, where it could be undefined ?

**Comment by JMorocho23** [comment]
So currently this is the way i have it set up, im using the PullToRefresh component to refresh the page, but the error right now happens while its in the proccess of refreshing didnt even notice the error till turned on "Perserve Error logs" in Chrome   
![image](https://user-images.githubusercontent.com/26604996/109060883-f36a8500-76b3-11eb-9217-4217dc5ba7ac.png)

**Comment by thmsgbrt** [comment]
Interesting...
I'm gonna give it a look later today, thanks!

**Comment by thmsgbrt** [comment]
@JMorocho23 Hi there,

So the problem is that onRefresh is expecting a Promise, which is not what you are passing.
You could do it as follow:

`          onRefresh={() =>
            Promise.resolve().then(() => {
              window.location.reload();
            })
          }`

**Comment by JMorocho23** [comment]
@thmsgbrt  Thank you so much, that worked!
