### ISSUE TITLE
[Question] The loading always here when I am pull

### ISSUE THREAD

**Issue by elowes** [thmsgbrt/react-simple-pull-to-refresh#4]
![image](https://user-images.githubusercontent.com/8766034/81881586-1d3e3980-95c3-11ea-925f-977fc1fe5584.png)

How to hide it. In my opinion, the onRefresh should be a function that return a promise. When the promise resolved or rejected. The loading hide itself.

**Comment by thmsgbrt** [comment]
Hi @elowes !
Sorry for the delay, I'm gonna investigate that, thanks.

**Comment by thmsgbrt** [comment]
Hi @elowes,

I believe this happens when what is provided as a children of pull-to-refresh doesn't change after refreshing data. This is indeed not an expected behaviour.

**Comment by thmsgbrt** [comment]
@elowes 
I believe you are now using a library since I took forever to fix it ;).
Anyway, I published a version 1.2.0 that now require onRefresh and onFetchMore to be Promises.

Thank you for your feedback and input!
