### ISSUE TITLE
Cannot use in react@18.2.0

### ISSUE THREAD

**Issue by ShunShanIT** [thmsgbrt/react-simple-pull-to-refresh#62]
I am starting a new project, and want to use this in my project. but seems not available in react@18.2.0

**Comment by nitz-iron** [comment]
same...

**Comment by jatinhemnani01** [comment]
any solution?

**Comment by thmsgbrt** [comment]
I'm gonna do some tests this weekend, see if there is any bug

**Comment by thmsgbrt** [comment]
Hi guys, I've published 1.3.3, it should now work with React 18 as well 👍
