### ISSUE TITLE
After Upgrade to 1.3.1 getting error that module not found

### ISSUE THREAD

**Issue by djaffer** [thmsgbrt/react-simple-pull-to-refresh#64]
ModuleNotFoundError
Could not find module in path: 'react-simple-pull-to-refresh' relative to '/src/App.js'

**Comment by patotoma** [comment]
same for me

**Comment by thmsgbrt** [comment]
Will give a look later today, sorry guys. Please use 1.3.0 meanwhile

**Comment by thmsgbrt** [comment]
Hi,

I've published 1.3.2, it should work again.
I've been publishing the 1.3.1 too fast yesterday and I actually forgot to run the build script before publishing.

Sincere apologies.
