### ISSUE TITLE
Cannot read properties of undefined (reading 'then') 

### ISSUE THREAD

**Issue by CalvinJamesHeath** [thmsgbrt/react-simple-pull-to-refresh#83]
```
<PullToRefresh onRefresh={() => console.log('aaa')}>
	<ul>
		{list.map((item, index) => (
			<li key={index}>{item}</li>
		))}
	</ul>
</PullToRefresh>;
```
**Version:** "react-simple-pull-to-refresh": "^1.3.3",
_React:_ "react": "^17.0.2"

Each time I scroll down I get the following error ("Uncaught TypeError: Cannot read properties of undefined (reading 'then') at HTMLDivElement.onEnd (index.esm.js:280:1)"). 

Perhaps I'm doing something wrong. Thanks!

**Comment by thatchapitNB** [comment]
onRefresh type is "() => Promise".
 You can use  ` const getNewData = (): Promise<void> => {
    return new Promise(res => {
      setTimeout(() => {
        res(setList([...list, ...FAKE_LIST]));
      }, 1500);
    });
  };`  or using 'async' function.

**Comment by CalvinJamesHeath** [comment]
Thanks!
